In [61]:
import numpy as np
import pandas as pd
import math

In [62]:
import random

In [63]:
x1=[random.uniform(1,100) for i in range(45)]

x2=[random.uniform(1,100) for i in range(45)]

y=random.choices([0,1],k=45)

In [64]:
df=pd.DataFrame(
    {
        "x1":x1,
        "x2":x2,
        "y":y
    }
)

In [65]:
df

           x1         x2  y
0   57.825383  24.427219  1
1   17.145518   8.016140  1
2   25.010360   6.457440  1
3   76.244056   2.228469  1
4   54.927261  82.714148  1
5   74.082227  25.255953  0
6   58.362046  54.947244  1
7   64.887967  44.059623  0
8   78.185999  86.367028  1
9   33.444478  94.390938  0
10  52.118499  13.245271  0
11  79.375061  28.343852  0
12  94.592130  80.182394  1
13  36.252217  45.106345  1
14  79.457912  13.023812  0
15  51.707996  10.546299  0
16  70.447587  74.778297  1
17  37.875963   8.131184  1
18  50.044261  64.384943  0
19   9.502966  50.462258  1
20   6.590482  81.394951  0
21  65.674435  66.568521  1
22  77.341826  52.899821  1
23  55.522353  95.291778  0
24  25.093363  84.498199  0
25  58.090725  23.555586  0
26  63.047167  54.976124  1
27  44.576208  77.369503  0
28   7.719485  24.030829  0
29  24.852070  60.139788  1
30  72.472412  59.777229  1
31  89.890346  98.337756  0
32  13.010411  81.604288  0
33  57.964190  56.150868  1
34  59.039225  96.889871  0
35  74.488839   6.641803  0
36  49.845580  36.663095  1
37  52.071872  15.381478  1
38  29.814122   3.874394  1
39  20.147359  23.382223  0
40  31.534201   6.387608  1
41  89.386021  70.840224  0
42  95.623656  27.639133  0
43  90.404357  68.052439  0
44  50.524283  51.506204  1

In [66]:
x=df[['x1','x2']]

In [67]:
y=df['y']

In [68]:
x

           x1         x2
0   57.825383  24.427219
1   17.145518   8.016140
2   25.010360   6.457440
3   76.244056   2.228469
4   54.927261  82.714148
5   74.082227  25.255953
6   58.362046  54.947244
7   64.887967  44.059623
8   78.185999  86.367028
9   33.444478  94.390938
10  52.118499  13.245271
11  79.375061  28.343852
12  94.592130  80.182394
13  36.252217  45.106345
14  79.457912  13.023812
15  51.707996  10.546299
16  70.447587  74.778297
17  37.875963   8.131184
18  50.044261  64.384943
19   9.502966  50.462258
20   6.590482  81.394951
21  65.674435  66.568521
22  77.341826  52.899821
23  55.522353  95.291778
24  25.093363  84.498199
25  58.090725  23.555586
26  63.047167  54.976124
27  44.576208  77.369503
28   7.719485  24.030829
29  24.852070  60.139788
30  72.472412  59.777229
31  89.890346  98.337756
32  13.010411  81.604288
33  57.964190  56.150868
34  59.039225  96.889871
35  74.488839   6.641803
36  49.845580  36.663095
37  52.071872  15.381478
38  29.814122   3.874394
39  20.147359  23.382223
40  31.534201   6.387608
41  89.386021  70.840224
42  95.623656  27.639133
43  90.404357  68.052439
44  50.524283  51.506204

In [69]:
w=[0,0]
b=0

In [70]:
lr=0.001

In [71]:
def sigmoid(z):
  return 1/(1+(2.7182)**-z)

In [72]:
for j in range(1000):
  for i in range(len(x1)):
    x1c=x1[i]
    x2c=x2[i]
    z=np.dot(w,[x1c,x2c])+b
    y_pred=sigmoid(z)

    loss=(-1)*(y[i]*math.log(y_pred)+(1-y[i])*math.log(1-y_pred))
    error=y_pred-y[i]
    w[0]=w[0]-lr*(error)*x1c
    w[1]=w[1]-lr*(error)*x2c
    result=0
    b=b-lr*(error)
    if y_pred < 0.5:
      result=0
    elif y_pred >=0.5:
      result=1
  print(f" result:{result} | Loss:{loss} | w1:{w[0]} | w2:{w[1]} | pred: {y_pred} | error:{error}")

 result:0 | Loss:6.302819892750479 | w1:0.007175871246558024 | w2:-0.028487127893712848 | pred: 0.0018311338886023729 | error:-0.9981688661113977
 result:0 | Loss:6.293718404206455 | w1:0.011392843442146514 | w2:-0.03245730209194389 | pred: 0.0018478760062357797 | error:-0.9981521239937642
 result:0 | Loss:6.286999691662579 | w1:0.01219822076608245 | w2:-0.03312557751292713 | pred: 0.0018603331550787522 | error:-0.9981396668449213
 result:0 | Loss:6.2854129529307965 | w1:0.012333811636250788 | w2:-0.03323546006137096 | pred: 0.0018632873609065123 | error:-0.9981367126390935
 result:0 | Loss:6.284820169636787 | w1:0.012354264178225521 | w2:-0.033251500565965944 | pred: 0.001864392213962861 | error:-0.9981356077860372
 result:0 | Loss:6.284398153842443 | w1:0.012355340803875355 | w2:-0.033251811332538656 | pred: 0.0018651791829690006 | error:-0.998134820817031
 result:0 | Loss:6.284005001964765 | w1:0.01235317174462714 | w2:-0.033249487107150956 | pred: 0.001865912625834764 | error:-0.9981340873741652
 result:0 | Loss:6.283616769263826 | w1:0.012350462736523522 | w2:-0.03324672172607595 | pred: 0.0018666371747709024 | error:-0.9981333628252291
 result:0 | Loss:6.283229429976396 | w1:0.012347667297345391 | w2:-0.03324388267299602 | pred: 0.0018673603367295464 | error:-0.9981326396632705
 result:0 | Loss:6.282842307938193 | w1:0.01234486142241032 | w2:-0.03324103150029398 | pred: 0.00186808337301177 | error:-0.9981319166269882
 result:0 | Loss:6.282455289822664 | w1:0.012342057839435316 | w2:-0.03323817851913314 | pred: 0.00186880649504008 | error:-0.9981311935049599
 result:0 | Loss:6.282068356857668 | w1:0.012339258674476994 | w2:-0.03323532545888467 | pred: 0.001869529737792418 | error:-0.9981304702622076
 result:0 | Loss:6.2816815061535225 | w1:0.012336464277248847 | w2:-0.03323247261177053 | pred: 0.0018702531065967487 | error:-0.9981297468934033
 result:0 | Loss:6.281294737487588 | w1:0.012333674699864523 | w2:-0.03322962002935585 | pred: 0.0018709766017993648 | error:-0.9981290233982006
 result:0 | Loss:6.280908051084513 | w1:0.012330889944591125 | w2:-0.03322676772290506 | pred: 0.0018717002229099583 | error:-0.9981282997770901
 result:0 | Loss:6.280521447243448 | w1:0.012328110005354713 | w2:-0.03322391569692972 | pred: 0.001872423969298009 | error:-0.998127576030702
 result:0 | Loss:6.28013492627542 | w1:0.012325334874693339 | w2:-0.033221063954804876 | pred: 0.0018731478403098305 | error:-0.9981268521596902
 result:0 | Loss:6.279748488492847 | w1:0.012322564544921484 | w2:-0.03321821249970975 | pred: 0.00187387183528817 | error:-0.9981261281647118
 result:0 | Loss:6.279362134207744 | w1:0.012319799008325388 | w2:-0.03321536133478502 | pred: 0.00187459595357556 | error:-0.9981254040464245
 result:0 | Loss:6.278975863731454 | w1:0.01231703825719542 | w2:-0.033212510463159 | pred: 0.0018753201945148406 | error:-0.9981246798054851
 result:0 | Loss:6.27858967737458 | w1:0.012314282283831628 | w2:-0.03320965988795222 | pred: 0.0018760445574492722 | error:-0.9981239554425507
 result:0 | Loss:6.278203575446991 | w1:0.01231153108054471 | w2:-0.0332068096122783 | pred: 0.0018767690417225336 | error:-0.9981232309582775
 result:0 | Loss:6.27781755825781 | w1:0.012308784639656067 | w2:-0.03320395963924378 | pred: 0.001877493646678746 | error:-0.9981225063533212
 result:0 | Loss:6.2774316261154235 | w1:0.012306042953497964 | w2:-0.033201109971948375 | pred: 0.0018782183716624648 | error:-0.9981217816283375
 result:0 | Loss:6.277045779327475 | w1:0.01230330601441331 | w2:-0.033198260613484895 | pred: 0.001878943216018677 | error:-0.9981210567839813
 result:0 | Loss:6.276660018200875 | w1:0.012300573814755814 | w2:-0.03319541156693928 | pred: 0.0018796681790928004 | error:-0.9981203318209072
 result:0 | Loss:6.276274343041791 | w1:0.012297846346889893 | w2:-0.033192562835390516 | pred: 0.0018803932602307015 | error:-0.9981196067397693
 result:0 | Loss:6.2758887541556625 | w1:0.012295123603190704 | w2:-0.03318971442191088 | pred: 0.001881118458778663 | error:-0.9981188815412213
 result:0 | Loss:6.275503251847179 | w1:0.012292405576044184 | w2:-0.0331868663295657 | pred: 0.0018818437740834326 | error:-0.9981181562259166
 result:0 | Loss:6.275117836420309 | w1:0.012289692257846895 | w2:-0.03318401856141346 | pred: 0.0018825692054921725 | error:-0.9981174307945079
 result:0 | Loss:6.274732508178277 | w1:0.012286983641006118 | w2:-0.0331811711205058 | pred: 0.0018832947523524971 | error:-0.9981167052476475
 result:0 | Loss:6.274347267423583 | w1:0.012284279717939849 | w2:-0.03317832400988755 | pred: 0.0018840204140124531 | error:-0.9981159795859875
 result:0 | Loss:6.273962114457988 | w1:0.01228158048107672 | w2:-0.033175477232596715 | pred: 0.001884746189820532 | error:-0.9981152538101795
 result:0 | Loss:6.273577049582523 | w1:0.012278885922856038 | w2:-0.033172630791664465 | pred: 0.0018854720791256668 | error:-0.9981145279208743
 result:0 | Loss:6.273192073097489 | w1:0.012276196035727834 | w2:-0.0331697846901152 | pred: 0.0018861980812772314 | error:-0.9981138019187228
 result:0 | Loss:6.272807185302457 | w1:0.012273510812152694 | w2:-0.03316693893096649 | pred: 0.0018869241956250371 | error:-0.9981130758043749
 result:0 | Loss:6.2724223864962685 | w1:0.012270830244601912 | w2:-0.03316409351722907 | pred: 0.0018876504215193514 | error:-0.9981123495784806
 result:0 | Loss:6.272037676977039 | w1:0.01226815432555732 | w2:-0.033161248451906995 | pred: 0.001888376758310867 | error:-0.9981116232416891
 result:0 | Loss:6.271653057042154 | w1:0.012265483047511502 | w2:-0.03315840373799748 | pred: 0.0018891032053507384 | error:-0.9981108967946493
 result:0 | Loss:6.271268526988273 | w1:0.012262816402967523 | w2:-0.033155559378490955 | pred: 0.0018898297619905587 | error:-0.9981101702380094
 result:0 | Loss:6.270884087111332 | w1:0.012260154384439108 | w2:-0.033152715376371135 | pred: 0.0018905564275823624 | error:-0.9981094435724176
 result:0 | Loss:6.270499737706543 | w1:0.012257496984450528 | w2:-0.03314987173461496 | pred: 0.0018912832014786342 | error:-0.9981087167985213
 result:0 | Loss:6.2701154790683855 | w1:0.012254844195536678 | w2:-0.03314702845619257 | pred: 0.0018920100830323182 | error:-0.9981079899169677
 result:0 | Loss:6.26973131149063 | w1:0.012252196010242987 | w2:-0.033144185544067464 | pred: 0.001892737071596783 | error:-0.9981072629284032
 result:0 | Loss:6.269347235266312 | w1:0.012249552421125458 | w2:-0.033141343001196394 | pred: 0.0018934641665258676 | error:-0.9981065358334741
 result:0 | Loss:6.268963250687754 | w1:0.01224691342075064 | w2:-0.0331385008305293 | pred: 0.001894191367173847 | error:-0.9981058086328262
 result:0 | Loss:6.268579358046557 | w1:0.012244279001695564 | w2:-0.033135659035009556 | pred: 0.0018949186728954503 | error:-0.9981050813271045
 result:0 | Loss:6.268195557633598 | w1:0.012241649156547865 | w2:-0.03313281761757368 | pred: 0.0018956460830458592 | error:-0.9981043539169542
 result:0 | Loss:6.267811849739038 | w1:0.012239023877905666 | w2:-0.03312997658115161 | pred: 0.0018963735969807106 | error:-0.9981036264030193
 result:0 | Loss:6.26742823465232 | w1:0.012236403158377561 | w2:-0.03312713592866648 | pred: 0.0018971012140560873 | error:-0.9981028987859439
 result:0 | Loss:6.267044712662174 | w1:0.012233786990582682 | w2:-0.0331242956630349 | pred: 0.0018978289336285198 | error:-0.9981021710663714
 result:0 | Loss:6.266661284056606 | w1:0.01223117536715062 | w2:-0.03312145578716663 | pred: 0.0018985567550550086 | error:-0.998101443244945
 result:0 | Loss:6.266277949122914 | w1:0.012228568280721427 | w2:-0.03311861630396491 | pred: 0.0018992846776929905 | error:-0.998100715322307
 result:0 | Loss:6.265894708147678 | w1:0.012225965723945645 | w2:-0.0331157772163262 | pred: 0.0019000127009003737 | error:-0.9980999872990997
 result:0 | Loss:6.265511561416764 | w1:0.012223367689484288 | w2:-0.0331129385271404 | pred: 0.0019007408240355103 | error:-0.9980992591759645
 result:0 | Loss:6.265128509215327 | w1:0.012220774170008775 | w2:-0.03311010023929076 | pred: 0.0019014690464572148 | error:-0.9980985309535428
 result:0 | Loss:6.26474555182781 | w1:0.012218185158200966 | w2:-0.03310726235565382 | pred: 0.001902197367524757 | error:-0.9980978026324753
 result:0 | Loss:6.264362689537943 | w1:0.012215600646753165 | w2:-0.033104424879099585 | pred: 0.0019029257865978645 | error:-0.9980970742134021
 result:0 | Loss:6.263979922628753 | w1:0.012213020628368022 | w2:-0.03310158781249143 | pred: 0.0019036543030367173 | error:-0.9980963456969633
 result:0 | Loss:6.263597251382547 | w1:0.012210445095758728 | w2:-0.033098751158686046 | pred: 0.0019043829162019691 | error:-0.998095617083798
 result:0 | Loss:6.26321467608093 | w1:0.012207874041648713 | w2:-0.03309591492053354 | pred: 0.0019051116254547203 | error:-0.9980948883745453
 result:0 | Loss:6.262832197004802 | w1:0.012205307458771887 | w2:-0.033093079100877554 | pred: 0.0019058404301565354 | error:-0.9980941595698435
 result:0 | Loss:6.262449814434351 | w1:0.012202745339872478 | w2:-0.03309024370255497 | pred: 0.0019065693296694412 | error:-0.9980934306703305
 result:0 | Loss:6.2620675286490615 | w1:0.012200187677705067 | w2:-0.033087408728396155 | pred: 0.0019072983233559273 | error:-0.9980927016766441
 result:0 | Loss:6.2616853399277135 | w1:0.012197634465034676 | w2:-0.03308457418122496 | pred: 0.001908027410578942 | error:-0.9980919725894211
 result:0 | Loss:6.261303248548382 | w1:0.012195085694636572 | w2:-0.03308174006385859 | pred: 0.0019087565907019005 | error:-0.9980912434092981
 result:0 | Loss:6.260921254788441 | w1:0.012192541359296344 | w2:-0.033078906379107736 | pred: 0.0019094858630886767 | error:-0.9980905141369113
 result:0 | Loss:6.260539358924558 | w1:0.012190001451810012 | w2:-0.03307607312977654 | pred: 0.0019102152271036183 | error:-0.9980897847728963
 result:0 | Loss:6.260157561232705 | w1:0.01218746596498383 | w2:-0.033073240318662656 | pred: 0.0019109446821115286 | error:-0.9980890553178885
 result:0 | Loss:6.259775861988151 | w1:0.012184934891634275 | w2:-0.033070407948557104 | pred: 0.0019116742274776733 | error:-0.9980883257725224
 result:0 | Loss:6.259394261465462 | w1:0.012182408224588291 | w2:-0.033067576022244465 | pred: 0.0019124038625678021 | error:-0.9980875961374321
 result:0 | Loss:6.259012759938509 | w1:0.01217988595668297 | w2:-0.03306474454250272 | pred: 0.001913133586748118 | error:-0.9980868664132518
 result:0 | Loss:6.258631357680465 | w1:0.012177368080765687 | w2:-0.03306191351210346 | pred: 0.0019138633993852898 | error:-0.9980861366006147
 result:0 | Loss:6.258250054963802 | w1:0.012174854589694119 | w2:-0.03305908293381166 | pred: 0.001914593299846469 | error:-0.9980854067001536
 result:0 | Loss:6.257868852060301 | w1:0.012172345476336166 | w2:-0.033056252810385905 | pred: 0.0019153232874992599 | error:-0.9980846767125008
 result:0 | Loss:6.2574877492410454 | w1:0.012169840733569942 | w2:-0.033053423144578216 | pred: 0.0019160533617117454 | error:-0.9980839466382883
 result:0 | Loss:6.257106746776428 | w1:0.012167340354283789 | w2:-0.0330505939391342 | pred: 0.0019167835218524706 | error:-0.9980832164781476
 result:0 | Loss:6.25672584493614 | w1:0.012164844331376337 | w2:-0.03304776519679297 | pred: 0.0019175137672904643 | error:-0.9980824862327096
 result:0 | Loss:6.256345043989183 | w1:0.012162352657756371 | w2:-0.03304493692028715 | pred: 0.0019182440973952246 | error:-0.9980817559026047
 result:0 | Loss:6.255964344203871 | w1:0.01215986532634282 | w2:-0.03304210911234294 | pred: 0.0019189745115367094 | error:-0.9980810254884633
 result:0 | Loss:6.255583745847825 | w1:0.0121573823300649 | w2:-0.033039281775680183 | pred: 0.0019197050090853595 | error:-0.9980802949909147
 result:0 | Loss:6.255203249187975 | w1:0.012154903661861921 | w2:-0.03303645491301214 | pred: 0.0019204355894120867 | error:-0.9980795644105879
 result:0 | Loss:6.254822854490561 | w1:0.012152429314683418 | w2:-0.03303362852704573 | pred: 0.00192116625188828 | error:-0.9980788337481117
 result:0 | Loss:6.254442562021135 | w1:0.012149959281489042 | w2:-0.033030802620481414 | pred: 0.001921896995885802 | error:-0.9980781030041141
 result:0 | Loss:6.254062372044562 | w1:0.012147493555248537 | w2:-0.03302797719601326 | pred: 0.0019226278207769886 | error:-0.998077372179223
 result:0 | Loss:6.253682284825023 | w1:0.01214503212894192 | w2:-0.03302515225632896 | pred: 0.0019233587259346525 | error:-0.9980766412740654
 result:0 | Loss:6.25330230062601 | w1:0.012142574995559208 | w2:-0.03302232780410981 | pred: 0.0019240897107320807 | error:-0.9980759102892679
 result:0 | Loss:6.252922419710329 | w1:0.01214012214810059 | w2:-0.033019503842030645 | pred: 0.00192482077454305 | error:-0.998075179225457
 result:0 | Loss:6.2525426423401065 | w1:0.012137673579576333 | w2:-0.03301668037275999 | pred: 0.001925551916741799 | error:-0.9980744480832582
 result:0 | Loss:6.252162968776786 | w1:0.012135229283006782 | w2:-0.03301385739896004 | pred: 0.001926283136703046 | error:-0.9980737168632969
 result:0 | Loss:6.251783399281121 | w1:0.012132789251422416 | w2:-0.033011034923286484 | pred: 0.0019270144338020088 | error:-0.998072985566198
 result:0 | Loss:6.251403934113191 | w1:0.012130353477863752 | w2:-0.03300821294838879 | pred: 0.0019277458074143633 | error:-0.9980722541925856
 result:0 | Loss:6.251024573532397 | w1:0.012127921955381343 | w2:-0.03300539147691005 | pred: 0.0019284772569162691 | error:-0.9980715227430837
 result:0 | Loss:6.250645317797452 | w1:0.012125494677035817 | w2:-0.03300257051148693 | pred: 0.0019292087816843793 | error:-0.9980707912183157
 result:0 | Loss:6.250266167166398 | w1:0.012123071635897861 | w2:-0.03299975005474994 | pred: 0.0019299403810958146 | error:-0.9980700596189042
 result:0 | Loss:6.2498871218965935 | w1:0.012120652825048171 | w2:-0.032996930109323086 | pred: 0.0019306720545281902 | error:-0.9980693279454718
 result:0 | Loss:6.249508182244727 | w1:0.012118238237577392 | w2:-0.032994110677824165 | pred: 0.0019314038013595897 | error:-0.9980685961986404
 result:0 | Loss:6.249129348466803 | w1:0.012115827866586375 | w2:-0.03299129176286465 | pred: 0.001932135620968597 | error:-0.9980678643790314
 result:0 | Loss:6.248750620818155 | w1:0.012113421705185722 | w2:-0.03298847336704967 | pred: 0.0019328675127342706 | error:-0.9980671324872658
 result:0 | Loss:6.2483719995534415 | w1:0.012111019746496227 | w2:-0.03298565549297814 | pred: 0.0019335994760361589 | error:-0.9980664005239639
 result:0 | Loss:6.247993484926648 | w1:0.012108621983648496 | w2:-0.03298283814324262 | pred: 0.001934331510254287 | error:-0.9980656684897458
 result:0 | Loss:6.24761507719109 | w1:0.012106228409783253 | w2:-0.03298002132042949 | pred: 0.0019350636147691717 | error:-0.9980649363852309
 result:0 | Loss:6.247236776599403 | w1:0.012103839018051066 | w2:-0.032977205027118726 | pred: 0.0019357957889618248 | error:-0.9980642042110381
 result:0 | Loss:6.24685858340356 | w1:0.01210145380161249 | w2:-0.03297438926588417 | pred: 0.0019365280322137318 | error:-0.9980634719677862
 result:0 | Loss:6.246480497854863 | w1:0.012099072753638002 | w2:-0.03297157403929333 | pred: 0.0019372603439068666 | error:-0.9980627396560932
 result:0 | Loss:6.246102520203942 | w1:0.012096695867308035 | w2:-0.03296875934990757 | pred: 0.0019379927234237065 | error:-0.9980620072765763
 result:0 | Loss:6.24572465070076 | w1:0.012094323135812893 | w2:-0.032965945200281906 | pred: 0.0019387251701472002 | error:-0.9980612748298529
 result:0 | Loss:6.245346889594611 | w1:0.012091954552352853 | w2:-0.03296313159296524 | pred: 0.0019394576834608026 | error:-0.9980605423165392
 result:0 | Loss:6.244969237134125 | w1:0.012089590110137993 | w2:-0.032960318530500125 | pred: 0.0019401902627484483 | error:-0.9980598097372515
 result:0 | Loss:6.24459169356727 | w1:0.01208722980238832 | w2:-0.03295750601542303 | pred: 0.0019409229073945587 | error:-0.9980590770926054
 result:0 | Loss:6.24421425914134 | w1:0.012084873622333743 | w2:-0.03295469405026415 | pred: 0.0019416556167840614 | error:-0.998058344383216
 result:0 | Loss:6.243836934102975 | w1:0.012082521563213926 | w2:-0.032951882637547524 | pred: 0.001942388390302358 | error:-0.9980576116096976
 result:0 | Loss:6.243459718698143 | w1:0.01208017361827856 | w2:-0.03294907177979098 | pred: 0.0019431212273353675 | error:-0.9980568787726646
 result:0 | Loss:6.243082613172156 | w1:0.012077829780787003 | w2:-0.032946261479506155 | pred: 0.0019438541272694802 | error:-0.9980561458727305
 result:0 | Loss:6.242705617769664 | w1:0.012075490044008555 | w2:-0.03294345173919858 | pred: 0.0019445870894915893 | error:-0.9980554129105084
 result:0 | Loss:6.242328732734657 | w1:0.012073154401222308 | w2:-0.03294064256136758 | pred: 0.001945320113389079 | error:-0.9980546798866109
 result:0 | Loss:6.241951958310463 | w1:0.012070822845717089 | w2:-0.032937833948506294 | pred: 0.0019460531983498319 | error:-0.9980539468016502
 result:0 | Loss:6.241575294739755 | w1:0.012068495370791646 | w2:-0.03293502590310181 | pred: 0.0019467863437622268 | error:-0.9980532136562378
 result:0 | Loss:6.241198742264545 | w1:0.012066171969754423 | w2:-0.03293221842763494 | pred: 0.0019475195490151398 | error:-0.9980524804509848
 result:0 | Loss:6.240822301126189 | w1:0.01206385263592373 | w2:-0.03292941152458054 | pred: 0.0019482528134979397 | error:-0.998051747186502
 result:0 | Loss:6.240445971565393 | w1:0.012061537362627515 | w2:-0.032926605196407215 | pred: 0.0019489861366004902 | error:-0.9980510138633996
 result:0 | Loss:6.240069753822196 | w1:0.012059226143203615 | w2:-0.032923799445577474 | pred: 0.001949719517713167 | error:-0.9980502804822868
 result:0 | Loss:6.239693648135995 | w1:0.012056918970999482 | w2:-0.032920994274547755 | pred: 0.0019504529562268276 | error:-0.9980495470437731
 result:0 | Loss:6.239317654745526 | w1:0.012054615839372472 | w2:-0.0329181896857684 | pred: 0.0019511864515328412 | error:-0.9980488135484672
 result:0 | Loss:6.238941773888876 | w1:0.012052316741689537 | w2:-0.03291538568168366 | pred: 0.0019519200030230714 | error:-0.998048079996977
 result:0 | Loss:6.238566005803482 | w1:0.012050021671327356 | w2:-0.03291258226473168 | pred: 0.00195265361008988 | error:-0.9980473463899101
 result:0 | Loss:6.238190350726126 | w1:0.01204773062167231 | w2:-0.03290977943734454 | pred: 0.001953387272126134 | error:-0.9980466127278739
 result:0 | Loss:6.237814808892941 | w1:0.012045443586120579 | w2:-0.03290697720194829 | pred: 0.0019541209885252054 | error:-0.9980458790114748
 result:0 | Loss:6.237439380539418 | w1:0.012043160558077907 | w2:-0.0329041755609629 | pred: 0.001954854758680955 | error:-0.998045145241319
 result:0 | Loss:6.237064065900392 | w1:0.01204088153095973 | w2:-0.032901374516802286 | pred: 0.00195558858198776 | error:-0.9980444114180123
 result:0 | Loss:6.236688865210051 | w1:0.01203860649819117 | w2:-0.03289857407187428 | pred: 0.0019563224578404968 | error:-0.9980436775421595
 result:0 | Loss:6.236313778701943 | w1:0.012036335453207037 | w2:-0.03289577422858079 | pred: 0.0019570563856345447 | error:-0.9980429436143654
 result:0 | Loss:6.235938806608966 | w1:0.012034068389451737 | w2:-0.032892974989317626 | pred: 0.001957790364765785 | error:-0.9980422096352343
 result:0 | Loss:6.235563949163375 | w1:0.012031805300379228 | w2:-0.032890176356474565 | pred: 0.001958524394630608 | error:-0.9980414756053694
 result:0 | Loss:6.2351892065967816 | w1:0.01202954617945328 | w2:-0.032887378332435435 | pred: 0.0019592584746259095 | error:-0.9980407415253741
 result:0 | Loss:6.234814579140153 | w1:0.012027291020147074 | w2:-0.032884580919578014 | pred: 0.0019599926041490873 | error:-0.9980400073958509
 result:0 | Loss:6.23444006702382 | w1:0.012025039815943536 | w2:-0.032881784120274156 | pred: 0.001960726782598046 | error:-0.9980392732174019
 result:0 | Loss:6.234065670477463 | w1:0.012022792560335109 | w2:-0.032878987936889655 | pred: 0.001961461009371207 | error:-0.9980385389906288

In [73]:
from sklearn.linear_model import LogisticRegression

In [74]:
model=LogisticRegression()

In [75]:
model.fit(x,y)

LogisticRegression()

In [76]:
new=[[52.073215,	21.621001	]]

In [77]:
model.predict(new)

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([1])